"use client";

import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";
import { Input, Label, Select } from "@/components/ui/Field";
import type { Currency } from "@/generated/prisma/client";
import Link from "next/link";

type Entry = { year: number; month: number; institution: string; category: string; currency: Currency; value: number; contributions: number; withdrawals: number };
type DashboardRates = { usdToBrl: number; eurToBrl: number };
const MONTHS = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];

export function DashboardOverview({ initialEntries, initialYear, rates }: { initialEntries: Entry[]; initialYear: number; rates: DashboardRates }) {
  const [year, setYear] = useState(initialYear);
  const [entries, setEntries] = useState(initialEntries);
  const [institution, setInstitution] = useState("Todas");
  const [currency, setCurrency] = useState("Todas");

  async function changeYear(nextYear: number) {
    setYear(nextYear);
    const response = await fetch(`/api/portfolio?year=${nextYear}`);
    if (response.ok) setEntries(await response.json());
  }

  const filtered = entries.filter((entry) => (institution === "Todas" || entry.institution === institution) && (currency === "Todas" || entry.currency === currency));
  const institutions = Array.from(new Set(entries.map((entry) => entry.institution))).sort();
  const toBRL = (value: number, entryCurrency: Currency) => entryCurrency === "USD" ? value * rates.usdToBrl : entryCurrency === "EUR" ? value * rates.eurToBrl : value;
  const total = (month: number) => filtered.reduce((sum, entry) => sum + (entry.month === month ? toBRL(entry.value, entry.currency ?? "BRL") : 0), 0);
  const netFlow = (month: number) => filtered.reduce((sum, entry) => entry.month === month ? sum + toBRL((entry.contributions ?? 0) - (entry.withdrawals ?? 0), entry.currency ?? "BRL") : sum, 0);
  const previousBalance = total(0);
  const monthTotals = MONTHS.map((_, index) => total(index + 1));
  const recordedMonths = Array.from(new Set(filtered.filter((entry) => entry.month > 0).map((entry) => entry.month))).sort((a, b) => a - b);
  const latestIndex = recordedMonths.length ? recordedMonths[recordedMonths.length - 1] - 1 : -1;
  const latest = latestIndex >= 0 ? monthTotals[latestIndex] : previousBalance;
  const previous = latestIndex > 0 ? monthTotals[latestIndex - 1] : previousBalance;
  const variation = previous > 0 ? ((latest - previous - netFlow(latestIndex + 1)) / previous) * 100 : null;
  const totalYear = latest - previousBalance - monthTotals.reduce((sum, _, index) => sum + netFlow(index + 1), 0);
  const money = (value: number, code: Currency = "BRL") => value.toLocaleString("pt-BR", { style: "currency", currency: code });
  const currentMonth = latestIndex >= 0 ? latestIndex + 1 : 0;
  const currencyTotals = ["BRL", "USD", "EUR"].map((code) => ({ code, value: filtered.filter((entry) => entry.currency === code && entry.month === currentMonth).reduce((sum, entry) => sum + entry.value, 0), valueInBrl: filtered.filter((entry) => entry.currency === code && entry.month === currentMonth).reduce((sum, entry) => sum + toBRL(entry.value, entry.currency ?? "BRL"), 0) })).filter((item) => item.value > 0);
  const currentCurrencyTotal = currencyTotals.reduce((sum, item) => sum + item.valueInBrl, 0);
  const maxMonth = Math.max(latest, previousBalance, ...monthTotals, 1);
  const positions = Array.from(new Map(filtered.map((entry) => [`${entry.institution}|${entry.category}`, { institution: entry.institution, category: entry.category, currency: entry.currency ?? "BRL" as Currency }])).values()).map((position) => {
    const currentValue = filtered.filter((entry) => entry.institution === position.institution && entry.category === position.category && entry.month === currentMonth).reduce((sum, entry) => sum + entry.value, 0);
    const previousValue = filtered.filter((entry) => entry.institution === position.institution && entry.category === position.category && entry.month === (currentMonth === 0 ? 0 : currentMonth - 1)).reduce((sum, entry) => sum + entry.value, 0);
    const valueInBrl = toBRL(currentValue, position.currency);
    const currentEntry = filtered.find((entry) => entry.institution === position.institution && entry.category === position.category && entry.month === currentMonth);
    const netFlow = (currentEntry?.contributions ?? 0) - (currentEntry?.withdrawals ?? 0);
    const change = currentMonth > 0 && previousValue > 0 ? ((currentValue - previousValue - netFlow) / previousValue) * 100 : null;
    return { ...position, currentValue, valueInBrl, change };
  }).filter((position) => position.currentValue > 0).sort((a, b) => b.valueInBrl - a.valueInBrl);

  return <div className="flex flex-col gap-6">
    <header className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-primary font-semibold">Centro de análise</p><h1 className="text-3xl font-semibold mt-1">Dashboard do Patrimônio</h1><p className="text-sm text-muted mt-1">Uma leitura consolidada do Patrimônio mensal.</p></div><div className="flex items-center gap-3"><Link href="/patrimonio" className="text-sm text-primary hover:underline">Editar Patrimônio →</Link><div className="flex items-center gap-2"><Label htmlFor="dashboardYear">Ano</Label><Input id="dashboardYear" type="number" value={year} onChange={(event) => changeYear(Number(event.target.value))} className="w-28" /></div></div></header>
    <Card><CardContent className="pt-5"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><div><Label htmlFor="dashboardInstitution">Instituição</Label><Select id="dashboardInstitution" value={institution} onChange={(event) => setInstitution(event.target.value)}><option>Todas</option>{institutions.map((item) => <option key={item}>{item}</option>)}</Select></div><div><Label htmlFor="dashboardCurrency">Moeda</Label><Select id="dashboardCurrency" value={currency} onChange={(event) => setCurrency(event.target.value)}><option>Todas</option><option value="BRL">Real (BRL)</option><option value="USD">Dólar (USD)</option><option value="EUR">Euro (EUR)</option></Select></div></div><p className="text-xs text-muted mt-3">Filtros aplicados sobre {filtered.length} registros.</p></CardContent></Card>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><Card><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted">Patrimônio atual (BRL)</p><p className="text-2xl font-semibold mt-2">{money(latest)}</p><p className="text-xs text-muted mt-1">último mês consolidado</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted">Saldo ano anterior (BRL)</p><p className="text-2xl font-semibold mt-2">{money(previousBalance)}</p><p className="text-xs text-muted mt-1">base de comparação</p></CardContent></Card><Card><CardContent className="pt-5"><p className={`text-xs uppercase tracking-wide ${variation === null || variation >= 0 ? "text-success" : "text-danger"}`}>Variação (%)</p><p className={`text-2xl font-semibold mt-2 ${variation === null || variation >= 0 ? "text-success" : "text-danger"}`}>{variation === null ? "-" : `${variation.toFixed(2)}%`}</p><p className="text-xs text-muted mt-1">sobre o mês anterior</p></CardContent></Card><Card><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted">Resultado nominal (BRL)</p><p className={`text-2xl font-semibold mt-2 ${totalYear >= 0 ? "text-success" : "text-danger"}`}>{totalYear >= 0 ? "+" : ""}{money(totalYear)}</p><p className="text-xs text-muted mt-1">conversão cambial aplicada</p></CardContent></Card></div>
    <div className="grid grid-cols-1 xl:grid-cols-[1.5fr_1fr] gap-4"><Card><CardHeader><CardTitle>Evolução do patrimônio (BRL)</CardTitle></CardHeader><CardContent><p className="text-xs text-muted mb-3">Consolidado com 1 USD = {money(rates.usdToBrl)} e 1 EUR = {money(rates.eurToBrl)}.</p><div className="h-64 flex items-end gap-2 border-b border-border">{monthTotals.map((value, index) => <div key={MONTHS[index]} className="flex-1 h-full flex flex-col justify-end items-center gap-2"><span className="text-[10px] text-muted truncate max-w-full">{value ? money(value) : "-"}</span><div className="w-full max-w-12 rounded-t-md bg-primary/80" style={{ height: `${Math.max(value ? 5 : 0, (value / maxMonth) * 100)}%` }} /><span className="text-xs text-muted">{MONTHS[index]}</span></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Composição por moeda</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><p className="text-xs text-muted">Saldo do último mês disponível: {currentMonth === 0 ? "ano anterior" : MONTHS[currentMonth - 1]}.</p>{currencyTotals.map((item) => { const factor = item.code === "USD" ? rates.usdToBrl : item.code === "EUR" ? rates.eurToBrl : 1; const share = currentCurrencyTotal > 0 ? (item.valueInBrl / currentCurrencyTotal) * 100 : 0; return <div key={item.code} className="rounded-lg border border-border bg-background/40 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary">{item.code}</p><p className="text-xl font-semibold mt-1">{money(item.value, item.code as Currency)}</p></div><span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-medium text-primary">{share.toFixed(1)}%</span></div><div className="mt-3 space-y-1 text-xs text-muted"><p>Equivalente: <strong className="text-foreground">{money(item.valueInBrl)}</strong></p><p>Conversão: <strong className="text-foreground">1 {item.code} = {money(factor)} BRL</strong></p></div><div className="mt-3 h-2 rounded-full bg-surface-muted overflow-hidden"><div className="h-full rounded-full bg-primary" style={{ width: `${share}%` }} /></div></div>; })}{!currencyTotals.length && <p className="text-sm text-muted">Nenhum valor registrado.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Instituições e concentração (BRL)</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted"><th className="py-3">Instituição</th><th className="py-3 text-right">Linhas</th><th className="py-3 text-right">Patrimônio atual (BRL)</th><th className="py-3 text-right">Participação (%)</th></tr></thead><tbody>{institutions.filter((item) => institution === "Todas" || item === institution).map((item) => { const value = filtered.filter((entry) => entry.institution === item && entry.month === latestIndex + 1).reduce((sum, entry) => sum + toBRL(entry.value, entry.currency ?? "BRL"), 0); return <tr key={item} className="border-b border-border"><td className="py-3 font-medium">{item}</td><td className="py-3 text-right">{new Set(filtered.filter((entry) => entry.institution === item).map((entry) => entry.category)).size}</td><td className="py-3 text-right">{money(value)}</td><td className="py-3 text-right">{latest > 0 ? `${((value / latest) * 100).toFixed(1)}%` : "-"}</td></tr>; })}</tbody></table></CardContent></Card>
    <Card><CardHeader><CardTitle>Posições detalhadas</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted"><th className="py-3">Instituição</th><th className="py-3">Aplicação</th><th className="py-3">Moeda</th><th className="py-3 text-right">Saldo atual</th><th className="py-3 text-right">Equivalente BRL</th><th className="py-3 text-right">Variação (%)</th></tr></thead><tbody>{positions.map((position) => <tr key={`${position.institution}|${position.category}`} className="border-b border-border"><td className="py-3">{position.institution}</td><td className="py-3 font-medium">{position.category}</td><td className="py-3">{position.currency}</td><td className="py-3 text-right">{money(position.currentValue, position.currency)}</td><td className="py-3 text-right">{money(position.valueInBrl)}</td><td className={`py-3 text-right ${position.change === null || position.change >= 0 ? "text-success" : "text-danger"}`}>{position.change === null ? "-" : `${position.change.toFixed(2)}%`}</td></tr>)}</tbody></table>{!positions.length && <p className="text-sm text-muted py-4">Nenhuma posição encontrada para os filtros atuais.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Resumo mensal detalhado (BRL)</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted"><th className="py-3">Mês</th><th className="py-3 text-right">Patrimônio (BRL)</th><th className="py-3 text-right">Movimentação (BRL)</th><th className="py-3 text-right">Rentabilidade (%)</th></tr></thead><tbody>{monthTotals.map((value, index) => { const previousValue = index === 0 ? previousBalance : monthTotals[index - 1]; const flow = netFlow(index + 1); const change = previousValue > 0 ? ((value - previousValue - flow) / previousValue) * 100 : null; return <tr key={MONTHS[index]} className="border-b border-border"><td className="py-3 font-medium">{MONTHS[index]}</td><td className="py-3 text-right">{value ? money(value) : "-"}</td><td className={`py-3 text-right ${flow >= 0 ? "text-success" : "text-danger"}`}>{flow === 0 ? "-" : `${flow > 0 ? "+" : ""}${money(flow)}`}</td><td className={`py-3 text-right ${change === null || change >= 0 ? "text-success" : "text-danger"}`}>{change === null ? "-" : `${change.toFixed(2)}%`}</td></tr>; })}</tbody></table></CardContent></Card>
  </div>;
}